# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  createyourideas-app:
    image: createyourideas
    environment:
      - _JAVA_OPTIONS=-Xmx4096m -Xms512m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://createyourideas-mysql:3306/createyourideas?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://createyourideas-mysql:3306/createyourideas?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://keycloak.createyourevent.org/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=9f608490-949a-4d83-95b0-f77c64f374bc
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 37090:8080

  createyourideas-mysql:
    image: mysql:5.7
    volumes:
      - db-data-createyourideas:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ihMMuka8243
      MYSQL_DATABASE: createyourideas
      MYSQL_USER: createyourideas
      MYSQL_PASSWORD: ihMMuka8243
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 37306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

volumes:
  db-data-createyourideas:
    external: true
